"""Build fixed demo cases by provenance/ID, never by detector performance."""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def rows(path):
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def build():
    groups = {}
    for row in rows(ROOT / "data/authorship/experiments/hc3-v1/records.jsonl"):
        if row["split"] == "test" and 90 <= row["word_count"] <= 220 and row["excerpt_kind"] != "first_250_word_excerpt_may_end_mid_sentence":
            groups.setdefault(row["source_group"], {})[row["label"]] = row
    pair = next(value for _, value in sorted(groups.items()) if set(value) == {0, 1})
    hc3 = json.loads((ROOT / "data/authorship/hc3-wiki/manifest.json").read_text(encoding="utf-8"))
    aide = json.loads((ROOT / "data/authorship/aide/manifest.json").read_text(encoding="utf-8"))
    examples = []

    def add(case_id, title, text, provenance, purpose, expected):
        examples.append({"id": case_id, "title": title, "text": text,
                         "text_sha256": hashlib.sha256(text.encode()).hexdigest(),
                         "provenance": provenance, "purpose": purpose, "expected_behavior": expected})

    for label, name in ((0, "human"), (1, "ai")):
        record = pair[label]
        add("hc3-" + name, "Published human explanation" if label == 0 else "Documented ChatGPT explanation", record["text"],
            {"kind": "documented_" + name, "description": "HC3 labels this excerpt as a Wikipedia human answer." if label == 0 else "HC3 records this as a ChatGPT answer; exact model version is unknown.",
             "record_id": record["id"], "url": hc3["official_url"], "license": hc3["license_id"],
             "license_url": hc3["license_url"], "attribution": hc3["attribution"], "modification": "Unchanged frozen excerpt."},
            "Compare two independently labeled answers to the same question.",
            "Run the detector before comparing its result with the documented origin. This is a demo from an already-observed diagnostic set, not a new accuracy test.")

    selected = None
    for record in sorted(rows(ROOT / "data/authorship/aide/records.jsonl"), key=lambda item: item["id"]):
        if record["label"] == "human":
            paragraph = next((part.strip() for part in re.split(r"\n\s*\n", record["text"]) if 90 <= len(part.split()) <= 220), None)
            if paragraph:
                selected = record, paragraph
                break
    record, paragraph = selected
    add("student-human", "Human-labeled student writing", paragraph,
        {"kind": "documented_human", "description": "The public AIDE release labels this student essay as human. Student identity and author independence are not established.",
         "record_id": record["id"], "url": aide["official_release_url"], "license": aide["license_id"],
         "license_url": aide["license_url"], "attribution": aide["attribution"], "modification": "One complete paragraph extracted without rewriting."},
        "Check how the detector handles student grammar, quotations and argumentation.",
        "A false AI flag here is a diagnostic failure worth recording; a human result on one example is not an accuracy guarantee.")

    mixed = pair[0]["text"] + "\n\n" + pair[1]["text"]
    add("constructed-mixed", "Constructed human + AI passage", mixed,
        {"kind": "synthetic_mixed", "description": "Constructed by placing the human explanation above the ChatGPT explanation. This is not a real human-editing workflow.",
         "record_ids": [pair[0]["id"], pair[1]["id"]], "url": hc3["official_url"], "license": hc3["license_id"],
         "license_url": hc3["license_url"], "attribution": hc3["attribution"], "modification": "Two unchanged excerpts concatenated with a blank line."},
        "Inspect changing context-block signals and whether the entire passage was analyzed.",
        "Block signals may vary. The application must not claim that disagreement establishes mixed authorship or exact sentence provenance.")

    app = (ROOT / "web/app.js").read_text(encoding="utf-8")
    urban = re.search(r"const SAMPLE = '([^']+)';", app).group(1)
    add("assistant-challenge", "AI-generated challenge passage", urban,
        {"kind": "documented_ai", "description": "Generated by the project assistant for the earlier demo. Retained even when detector results are uncertain.", "attribution": "TuringTint project assistant."},
        "Check a known AI example that the earlier build could not classify conclusively.",
        "Known origin is shown as fixture information only. The detector receives the text, not this label, and may still return inconclusive.")

    practice = "In my personal opinion, I think that students should plan ahead in advance before they begin studying. Our survey included 120 students, and 36 reported sleeping fewer than 6 hours. This small survey proves that every student learns better online. The results of the survey were collected together and combined into a single summary. These observations describe the surveyed group; they do not establish what caused the reported sleep patterns. The report should distinguish observations from explanations, preserve the sample size, and state which claims require additional evidence."
    add("revision-practice", "Revision practice: clarity and evidence", practice,
        {"kind": "writing_fixture", "description": "Synthetic editing exercise written by the project assistant, with deliberately redundant and overstated sentences.", "attribution": "TuringTint project assistant; all study details are fictional test data."},
        "Try the writing coach, preview a proposed edit, apply it and compare the revised analysis.",
        "Useful edits shorten redundancy or soften the unsupported causal claim while preserving 120 students, 36 responses and 6 hours. Authorship scores need not improve.")
    return {"version": 1, "selection_policy": "First lexicographically sorted paired HC3 test family with complete 90-220-word excerpts; first eligible AIDE human record/paragraph. Original AI challenge retained. No score-based selection.", "examples": examples}


if __name__ == "__main__":
    destination = ROOT / "evaluation/fixtures/demo-cases.json"
    destination.parent.mkdir(parents=True, exist_ok=True)
    result = build()
    destination.write_text(json.dumps(result, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps({"examples": len(result["examples"]), "selection_policy": result["selection_policy"]}))
